source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'app' do
  # Pods for app
  pod 'shared', :path => '../shared'
end